#!/bin/bash

echo "=================================================="
echo "🔐 GITHUB SECRETS CONFIGURATION"
echo "=================================================="
echo ""
echo "Go to: https://github.com/VaghasiyaAbhi/crypto-tracker/settings/secrets/actions"
echo ""
echo "Click 'New repository secret' and add these 3 secrets:"
echo ""
echo "=================================================="
echo "SECRET 1: SERVER_HOST"
echo "=================================================="
echo "Name: SERVER_HOST"
echo "Value (copy this):"
echo ""
echo "46.62.216.158"
echo ""
echo "=================================================="
echo "SECRET 2: SERVER_USER"
echo "=================================================="
echo "Name: SERVER_USER"
echo "Value (copy this):"
echo ""
echo "root"
echo ""
echo "=================================================="
echo "SECRET 3: SSH_PRIVATE_KEY"
echo "=================================================="
echo "Name: SSH_PRIVATE_KEY"
echo "Value (copy ENTIRE content below, including BEGIN and END lines):"
echo ""
cat ~/.ssh/id_ed25519_nopass
echo ""
echo "=================================================="
echo "✅ SETUP COMPLETE!"
echo "=================================================="
echo ""
echo "Next steps:"
echo "1. Add all 3 secrets to GitHub"
echo "2. Make a test commit and push"
echo "3. Watch deployment at: https://github.com/VaghasiyaAbhi/crypto-tracker/actions"
echo ""
